name: Docker

on:
  workflow_dispatch:
  push:
    tags:
      - '*.*.*'

env:
  REGISTRY: ghcr.io

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Delete All Old Images
        uses: dataaxiom/ghcr-cleanup-action@v1
        with:
          keep-n-untagged: 0
          package: ${{ github.event.repository.name }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/checkout@v4

      # https://github.com/docker/setup-buildx-action
      - name: Set Up Docker Buildx
        uses: docker/setup-buildx-action@b5ca514318bd6ebac0fb2aedd5d36ec1b5c232a2 # v3.10.0

      # https://github.com/docker/login-action
      - name: Log Into Registry ${{ env.REGISTRY }}
        uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d # v3.0.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # https://github.com/docker/metadata-action
      - name: Extract Docker Metadata
        id: meta
        uses: docker/metadata-action@96383f45573cb7f253c731d3b3ab81c87ef81934 # v5.0.0
        with:
          images: ${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ github.event.repository.name }}
          tags: |
            type=raw,value=${{ github.ref_name }}
            type=raw,value=latest

      # https://github.com/docker/build-push-action
      - name: Build and Push Docker Image
        id: build-and-push
        uses: docker/build-push-action@0565240e2d4ab88bba5387d719585280857ece09 # v5.0.0
        with:
          context: .
          push: true
          file: Dockerfile
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
