name: Docker

on:
  workflow_dispatch:
  push:
    tags:
      - '*.*.*'

env:
  REGISTRY: ghcr.io

jobs:
  build-and-push:
    permissions:
      contents: read
      packages: write
    uses: adamanteye/actions/.github/workflows/docker.yml@master
    with:
      name: ${{ github.event.repository.name }}
      label: ${{ github.ref_name }}
      owner: ${{ github.repository_owner }}
